### ISSUE TITLE
Is register_gis compatible with sparkR.session()?

### ISSUE THREAD

**Issue by MJRichard** [harryprince/geospark#12]
Starting with spark 2.0 the spark connection is created through sparkR.session but the documentation used the older connection.
```
conf <- spark_config()
sc <- spark_connect(master = "local", config = conf)
register_gis(sc)
```
Is register_gis() compatible with sparkR.session()?

**Comment by harryprince** [comment]
@MJRichard do you means `SparkR` sparkR.seesion function?
