### ISSUE TITLE
Availability for Spark >= 3.0

### ISSUE THREAD

**Issue by mrecos** [harryprince/geospark#19]
Hello, Thanks for making this R binding! I have been working to get this functional with Spark >= 3.0 and Apache Sedona on Databricks. An issue with using Spark 2.x is that the current {sf} package doesn't want to build with the GDAL library that resolves to Spark 2.x. This is all from my experimentation and there may be work arounds. However, it would be great to have this package updated or at least discussed how to work with the SNAPSHOT release of  Sedona/Geospark. Any help, dicussion, or resources would be very helpful! I will drop any info here if I get a breaktrhough.
Thanks,
Matt

**Comment by lorenzwalthert** [comment]
My use case is also databricks 😊. Would be great to see compatibility with spark > 3.0.0.

**Comment by lorenzwalthert** [comment]
My use case is also databricks 😊. Would be great to see compatibility with spark > 3.0.0.
